baseURL = "http://example.org/"
languageCode = "en-us"
title = "Abstract Machines"
theme = "book"

enableGitInfo = true

[params]
BookRepo = 'https://github.com/BinderDavid/abstract-machines-script'
BookEditPath = 'edit'
