baseURL = "http://example.org/"
languageCode = "en-us"
title = "Abstract Machines"
theme = "book"

enableGitInfo = true

pygmentsCodefences = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe= true

[params]
BookRepo = 'https://github.com/BinderDavid/abstract-machines-script'
BookEditPath = 'blob/main'


