name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      # ----------------------------------------
      # Build Elm Applications
      # ----------------------------------------
      - name: Setup Elm
        uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - name: Run Elm compiler
        run: |
          cd elm-apps
          mkdir -p target
          elm make src/Main.elm  --optimize --output=target/elm.js
          cd ..
          mkdir -p static/javascript
          cp elm-apps/target/* static/javascript/
      # ----------------------------------------
      # Build Purescript Applications
      # ----------------------------------------
      - name: Setup Purescript
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "0.14.2"
          spago: "0.20.3"
      - name: Build Purescript
        run: |
          cd purescript-apps
          spago bundle-app --to purescript.js
          cd ..
          mkdir -p static/javascript
          cp purescript-apps/purescript.js static/javascript/
      # ----------------------------------------
      # Use Hugo to build Website
      # ----------------------------------------
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify
      # ----------------------------------------
      # Deploy website
      # ----------------------------------------
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
